<a href="https://colab.research.google.com/github/Aryan-Tatiwar/TensorFlow_DeepLearning/blob/main/00_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Tensors


In [ ]:
import tensorflow as tf

print(tf.__version__)

2.19.0


In [ ]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of tensor (ndim)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check dimension of vector
vector.ndim

1

In [ ]:
# create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
#Check dimension of matrix
matrix.ndim

2

In [ ]:
#Create another matrix
another_matrix = tf.constant([[10.,7.],[3.,2.],[8.,9.]],dtype=tf.float16)# specifying datatype with tftensor
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Creating tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we have creatyed so far:



*   Scalar : a singlr number
*   Vector : a number with direction(eg. wind speed with direction)
*   Matrix : a 2-d arrayu of numbers
*   Tensor : an n-dimensional array of numbers (whetre n can be any number, 0-dimensional tensor id called as Sscalr, a 1-d tensor is called as vector)






# Creating tensors with `tf.Variable`

In [ ]:
# Craeting same tensor as with tf.Variable as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try change one of the elements in changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
#How about we try .assign
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:

#Lets's try change our unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor


# Creating random tensors

In [ ]:
#Creating two random but same tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproduceability
random_1 = random_1.normal(shape=(3,2)) #
random_1


In [ ]:

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

In [ ]:
#Are they equal?
random_1,random_2,random_1==random_2


# Shuffle the order of elements in tensor

In [ ]:
#Shuffle a tensor , valuable when u want to shuffle the data so that inherent order dosen't affect learning
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])
not_shuffled.ndim

It looks like if we want our shuffled tensors to be in the same order, we've got to use the global lvl and random lvl seed as well as the operation lvl random seed:

> Rule4 : If both global and operation seed ar set: Both seeds are used in
conjunction to determine the rnadom sequence.

In [ ]:
#Shuffle our not-shuffled tensor
tf.random.set_seed(42) #Global lvl random seed
tf.random.shuffle(not_shuffled, seed=42) # Local lvl random seed

# Other ways to make tensors

In [ ]:
#Create a tensor of all ones
tf.ones([10,7])


In [ ]:
#Create a tensor of all zeroes
tf.zeros(shape=(3,4))

###Turning numpy arrays into tensors

The main diff. between Numpy arrays and Tensorflow tensors is that tensors can be run on GPU much faster for numerical computing

In [ ]:
# Turning numpy arrays into tensor
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)# crates numpy array between 1 and 25
numpy_A


In [ ]:


A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)
A,B

# Getting information from tensors

*   Shape
*   Rank
*   Axis or Dimension
*   Size



In [ ]:
# Create a rank 4 tensor (4-d)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

In [ ]:
rank_4_tensor[0]

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

In [ ]:
# Get various attributes of tensor
print("Datatype of every element", rank_4_tensor.dtype)
print("Number of dimensions (rank)", rank_4_tensor.ndim)
print("Shape of tensor", rank_4_tensor.shape)
print("Elements along the 0 axis", rank_4_tensor.shape[0])
print("Elements along the last axis", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor", tf.size(rank_4_tensor))
print("Total number of elements in our tensor", tf.size(rank_4_tensor).numpy())

###Indexing tensors
Tensors can be indexed just like python lists.

In [ ]:
# Get first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

In [ ]:
#Get the first index from each dimension except the final one
rank_4_tensor[:1,:1,:1,:]

In [ ]:
# Create a rank 2 tensor
rank_2_tensor = tf.constant([[10,7],[3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

In [ ]:
# Get the last item of each of each row our rank 2 tensor
rank_2_tensor[:,-1]

In [ ]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0)

In [ ]:
tf.expand_dims(rank_2_tensor, axis=1)

# Manipulating tensors

**Basic operations**
+,-,*,/

In [ ]:
#We can add values to a tensor using the add operator
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

In [ ]:
# Original tensor is unchanged
tensor

In [ ]:
tensor * 10

In [ ]:
tensor - 10

In [ ]:
tensor/2

In [ ]:
# We can use the tensor flow built in function too
tf.multiply(tensor,10)

In [ ]:
tf.add(tensor,10)

# Matrix Multiplication

In ML, matrix multiplication is the most common tensor operations.

There are 2 rules our tensors must need to fulfill if we're going to matrix muktiply

1. The innner dimensions must match.
2. The resulting matrix have the shape of the outer dimensions

In [ ]:
# Matrix multiplication in tensor flow
tf.matmul(tensor,tensor)

In [ ]:
# Matrix multiplication with python operator '@'
tensor @ tensor

In [ ]:
tensor.shape

In [ ]:
# Cfreate a tensoe (3,2)
X = tf.constant([[1,2],[3,4],[5,6]])
Y = tf.constant([[7,8],[9,10],[11,12]])
X,Y

In [ ]:
# Try matrix multi of tensors of same shape
tf.matmul(X,Y)

In [ ]:
# Y = tf.constant([[7,8,9],[10,11,12]])
# tf.reshape(Y, shape=(2,3))

In [ ]:
# tf.matmul(X,Y)

In [ ]:
tf.transpose(Y)

In [ ]:
X

Instead of using reshape function we can use transpose for matrix multiplication as rehape function shuffles the elements in the tensor whereas transpose dosen't change the order of elements it just flips the tensor along its axis.

In [ ]:
tf.matmul(tf.transpose(X),Y)

# The dot product

In [ ]:
# Perform the dot product on X and Y , this requires either X or Y to be transposed
X,Y

In [ ]:
tf.tensordot(tf.transpose(X),Y,axes=1)

In [ ]:
# Perform matrix multiplication while transposing Y
tf.matmul(X,tf.transpose(Y))

In [ ]:
# Perform matrix multiplication between X and Y using reshape
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

In [ ]:
# Check the values of Y and transposed Y
print("Normal Y: ")
print(Y,"\n")
print("Y reshaped to (2,3): ")
print(tf.reshape(Y,(2,3)),"\n")
print("Y transposed: ")
print(tf.transpose(Y))

# Chganging the datatype of a tensor

In [ ]:
# Create a new tensor with default dtype (float)
B=tf.constant([1.7,7.4])
B.dtype

In [ ]:
C = tf.constant([7,10])
C.dtype

In [ ]:
# Change from float32 to float16, this is called reduced precision
D = tf.cast(B,dtype=tf.float16)
D

In [ ]:
# Change from int32 to float32
E = tf.cast(C,dtype=tf.float32)
E

# Aggregating Tensors

It means condensing tensors from multiple values down to a smaller amount of values

In [ ]:
# Getting the absolute values
D = tf.constant([-7,-10])
D

In [ ]:
tf.abs(D)

Let's go through the following forms of aggregation
* Get the minimum
* Get the maximum
* Get the meanof a tensor
* Get the sum of tensor

In [ ]:
# CReate a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100,size=50))
E

In [ ]:
tf.size(E), E.shape, E.ndim

In [ ]:
# Find the minimum
tf.reduce_min(E)

In [ ]:
# Find the maximum
tf.reduce_max(E)

In [ ]:
# Find the mean
tf.reduce_mean(E)

In [ ]:
# Find the sum
tf.reduce_sum(E)

In [ ]:
# Find the variance, we need to use the tensorflow_probability
import tensorflow_probability as tfp
tfp.stats.variance(E)

In [ ]:
# Find the Standard Deviation
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

# Find positional maximum and minimum of tensor

In [ ]:
# Craete a new tensor for finding positional max and min
tf.random.set_seed(42)
E = tf.random.uniform(shape=[50])
E

In [ ]:
# Find positional max
tf.argmax(E)

In [ ]:
# Index of oyur largest value position
E[tf.argmax(E)]

In [ ]:
# Find the mx value of E
tf.reduce_max(E)

In [ ]:
# Check for equality
E[tf.argmax(E)] == tf.reduce_max(E)

In [ ]:
# Find the positional min
tf.argmin(E)

In [ ]:
# Find the min using positional min index
E[tf.argmin(E)]

# Squeezing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

In [ ]:
G.shape

In [ ]:
g_squeezed = tf.squeeze(G)
g_squeezed, g_squeezed.shape


# One-hot encoding tensors

In [ ]:
# Create a list of indices
some_list = [0,1,2,3] # could be red, green, blue, purple

# One hot encode our list of indices
tf.one_hot(some_list,depth=4)


In [ ]:
# Specify custom val;ues for one hot encoding
tf.one_hot(some_list,depth=4,on_value="yo I love deep learning",off_value="I also like to dance")

# Squaring. Log, Squareroot

In [ ]:
#Create a new tensor
H = tf.range(1,10)
H

In [ ]:
# Square it
tf.square(H)

In [ ]:
# SquareRoot
tf.sqrt(tf.cast(H,dtype=tf.float32))

In [ ]:
# Find the log
tf.math.log(tf.cast(H,dtype=tf.float32))


# Tensors and NumPy

TensorFlow interacts beautifully with numpy arrays

In [ ]:
# Create a twnsor directly with numpy array
J = tf.constant(np.array([3.,7.,10.]))
J

In [ ]:
# Convert tensor back to NumPy array
np.array(J), type(np.array(J))

In [ ]:
# Convert tensor J to NumPy array
J.numpy(), type(J.numpy())

In [ ]:
# J = tf.constant([3.])
# J.numpy()[0]

In [ ]:
# The default Types of each are slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
# Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

# Finding access to GPUs

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Tue Nov 25 10:30:10 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   35C    P8              9W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

Note : If you've access toa CUDA enabled GPU, the tensorflow will use it automatically whenever possible